### ISSUE TITLE
OpenPredict responding to a query expecting biolink:Genes

### ISSUE THREAD

**Issue by CaseyTa** [MaastrichtU-IDS/translator-openpredict#25]
Translator testing issue: https://github.com/NCATSTranslator/testing/issues/115#event-5284365990
OpenPredict response: https://arax.ncats.io/?source=ARS&id=be1da25e-1060-4d5b-b30f-9a84f045edbb

The submitted query is between imatinib and biolink:Gene. OpenPredict correctly identifies imatinib, but responds to the gene node with biolink:Diseases.

**Comment by vemonet** [comment]
Thanks for the notice @CaseyTa ! I also noticed it during the last minihackathon, I just finished the fix, just need to test, and I will deploy in production tomorrow

There was a confusion when checking for the ancestors, we are now using the BL lookup API so that should be more reliable

**Comment by vemonet** [comment]
Fixed, and deployed in production!
