### ISSUE TITLE
Deploy 1.3

### ISSUE THREAD

**Issue by capasfield** [MaastrichtU-IDS/translator-openpredict#32]
https://arax.ncats.io/?smartapi=1 shows that Open Predict API has 1.2 in development (infores:openpredict)

Please deploy 1.3 of this tool into development ASAP.

**Comment by capasfield** [comment]
Fanstastic! Thank you for letting me know. I’ll update my notes accordingly.

-Carrie



Carrie Pasfield
Research Project Manager
Renaissance Computing Institute (RENCI)
University of North Carolina at Chapel Hill
***@***.***



From: Casey Ta ***@***.***>
Date: Tuesday, August 23, 2022 at 2:10 PM
To: MaastrichtU-IDS/translator-openpredict ***@***.***>
Cc: Pasfield, Carrie Anne ***@***.***>, Author ***@***.***>
Subject: Re: [MaastrichtU-IDS/translator-openpredict] Deploy 1.3 (Issue #32)

We've begun deploying OpenPredict to ITRB CI and Staging as per the current schedule.

**Comment by vemonet** [comment]
Hi @capasfield we updated the TRAPI version to 1.3 in development for OpenPredict, thanks for the notice!

**Comment by capasfield** [comment]
Great! Thanks for letting me know. I’ll update my notes.

-Carrie

Carrie Pasfield
Research Project Manager
Renaissance Computing Institute (RENCI)
University of North Carolina at Chapel Hill
***@***.***



From: Vincent Emonet ***@***.***>
Date: Wednesday, August 24, 2022 at 8:06 AM
To: MaastrichtU-IDS/translator-openpredict ***@***.***>
Cc: Pasfield, Carrie Anne ***@***.***>, Mention ***@***.***>
Subject: Re: [MaastrichtU-IDS/translator-openpredict] Deploy 1.3 (Issue #32)

Hi @capasfield<https://github.com/capasfield> we updated the TRAPI version to 1.3 in development for OpenPredict, thanks for the notice!
