### ISSUE TITLE
SmartAPI registration is missing the x-trapi info

### ISSUE THREAD

**Issue by CaseyTa** [MaastrichtU-IDS/translator-openpredict#49]
#### Describe the problem

The SmartAPI registration for OpenPredict is currently missing the x-trapi information. 
https://smart-api.info/ui/e9f69b81e755e163fdf6c41a2b5e07c0
https://smart-api.info/api/metadata/e9f69b81e755e163fdf6c41a2b5e07c0?raw=1

**Comment by vemonet** [comment]
Thanks!

**Comment by CaseyTa** [comment]
@vemonet This might still be an open issue. OpenPredict's [SmartAPI](https://smart-api.info/ui/e9f69b81e755e163fdf6c41a2b5e07c0) registration hasn't been updated since Aug 4. SmartAPI is indicating that the metadata source is invalid, which I'm assuming is why it's not updating.
