### ISSUE TITLE
"extra fields not permitted" when empty aux graph included in message

### ISSUE THREAD

**Issue by CaseyTa** [MaastrichtU-IDS/translator-openpredict#51]
#### Describe the problem

When Workflow Runner queries a TRAPI service, it includes an empty `auxiliary_graphs` object in the message. OpenPredict responds with 

```json
{
    "detail": [
        {
            "loc": [
                "body",
                "message",
                "auxiliary_graphs"
            ],
            "msg": "extra fields not permitted",
            "type": "value_error.extra"
        }
    ]
}
```

#### Provide the URL to the problematic OpenPredict API call

Tested in dev and CI environments 

#### To Reproduce

```json
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:Drug"
                    ]
                },
                "n1": {
                    "ids": [
                        "MONDO:0004979"
                    ],
                    "categories": [
                        "biolink:Disease"
                    ]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:treats"
                    ]
                }
            }
        },
        "auxiliary_graphs": {}
    },
    "workflow": [
        {
            "id": "lookup"
        }
    ],
    "submitter": "Workflow Runner"
}
```

Also occurs if `auxiliary_graphs` is `null`

#### Additional context

Currently a blocker for the CQS Path E query that targets OpenPredict. WFR needs to include the empty aux graphs to get around a current issue with how ARAX validates TRAPI based on 1.4.0 schema. Inclusion of an empty aux graph shouldn't affect how queries are performed, so it'd be helpful if OpenPredict can ignore empty or null aux graphs in the TRAPI query. Can this be accommodated?

**Comment by vemonet** [comment]
Hi @CaseyTa , the reasoner-pydantic package was not up to date, I fixed it on the dev server (should be fixed on CI soon), and I will ask to re-deploy on dev and prod

**Comment by CaseyTa** [comment]
Thanks, @vemonet! Tested working in dev and CI.
