### ISSUE TITLE
No score attribute on KG edges 

### ISSUE THREAD

**Issue by CaseyTa** [MaastrichtU-IDS/translator-openpredict#52]
#### Describe the problem

In queries to OpenPredict's `/query` endpoint, the knowledge graph edges do not contain the model prediction scores. It looks like the scores are only contained in the results analyses. The scores should also be contained in the edge attributes (in addition to score in the analyses). This would allow the scoring data to be retained if OpenPredict's edges get incorporated into other multihop results. I _think_ the score used to be present in edge attributes in previous versions of OpenPredict. 

#### Provide the URL to the problematic OpenPredict API call

Provide the full URL or `curl` command to reproduce the problematic call if applicable.

#### To Reproduce

The example `bioilnk:treated_by` and `biolink:similar_to` queries in the OpenAPI documentation reproduce this issue. Seen in dev, CI, and prod environments.

**Comment by vemonet** [comment]
Hi @CaseyTa yes it was present on the edges (which made sense to me), but then I was told they needed to be in the results. So I moved them to the results.

Now I think I understand that we need to duplicate many times all other the place the scores? 

Is this something permanent? It does not seems right for the Translator ecosystem. If we want TRAPI to be a way to exchange data efficiently and reliably, we should not rely on a language that promote so much failures and small errors by forcing to duplicate values in convoluted objects...

It is not hard for federators (ARA) to process a JSON response, and duplicate the values themselves if they need.

**Comment by vemonet** [comment]
I have pushed a fix, I'll updated tomorrow in dev, thanks for the notification

**Comment by CaseyTa** [comment]
Hi @vemonet, thanks for pushing the fix through already and for stating your concerns regarding TRAPI. The general structure of TRAPI makes sense to me, and I think it makes sense for us to duplicate the model prediction score for OpenPredict in both the edge attributes and in the results. 

In general, a single TRAPI result may be bound to one or more KG edges. In these cases, it's very likely that the score in the results will be some value that's not contained as an edge attribute from any single edge within the result, hence it makes sense to me that there's a score property in the result that's independent from other properties in the KG. 

Even for cases where the result is bound to a single KG edge, as in our case, I still think it makes sense to explicitly include the edge property and the result. The edge attributes can carry more EPC information than the results score, so trying to store it in the results only is insufficient. Also, a single edge may have multiple quantitative attributes (COHD does), and a client may not know natively which attribute should be used for scoring and ranking the results, hence it makes sense to explicitly fill in the results score even if the value is available as an edge attribute. 

Please let me know what you think.

**Comment by vemonet** [comment]
Oh ok, make sense! So that if you have a result with multiple edges, you could have a different scores for each edge, and another global score for the whole result. But since OpenPredict has only one edge the score for the result and the score for the edge are the same. 

Thanks @CaseyTa !
