### ISSUE TITLE
Setting the API Server URL bug in Docker container

### ISSUE THREAD

**Issue by vemonet** [MaastrichtU-IDS/translator-openpredict#9]
The `servers` url in the OpenAPI yaml definition is not changed by the provided arguments only when run in Docker containers

The exact same command:
`openpredict start-api --server-url http://myurl`

Works fine locally, the server URL is updated in the OpenAPI definition exposed

When run as entrypoint of a Docker... For some reason the arg is properly passed to the Python code, and the API is well started by the following line (with the right `server_url`):
```python
api.add_api('openapi.yml', arguments={'server_url': server_url})
```

But for some reason the started API has en EMPTY servers URL (not even a `/` which should be the default)

Seems to be an issue with Connexion

**Comment by vemonet** [comment]
Generalized issue in Connexion. Multiple issues have been created but the default behavior is to override `servers` whatever the situation, and Connexion do not provide any way to make sure the `servers` defined by the user in the `openapi.yml` file 

https://github.com/zalando/connexion/issues/1174
https://github.com/zalando/connexion/issues/1139
https://github.com/zalando/connexion/issues/1047

The culprit: https://github.com/zalando/connexion/blob/master/connexion/apis/flask_api.py#L310

It can be solved by adding a param to disable `_spec_for_prefix`

An `options` like `self.options.openapi_spec_path`

`self.options.disable_servers_overwrite = True`

Then check it in `_spec_for_prefix`

**Comment by vemonet** [comment]
Using https://pypi.org/project/flask-reverse-proxy-fix/ can help solve the issue

requirements.txt:
```
flask-reverse-proxy-fix
werkzeug<1
```

Code:
```python
from flask_reverse_proxy_fix.middleware import ReverseProxyPrefixFix

api = connexion.App(__name__, options={"swagger_url": ""}, arguments={'server_url': server_url})

api.add_api('openapi.yml')

api.app.config['REVERSE_PROXY_PATH'] = 'http://api.collaboratory.semantiscience.org'
ReverseProxyPrefixFix(api.app)

api.run(host='0.0.0.0', port=port, debug=debug, server=deployment_server)
```

**Comment by micheldumontier** [comment]
Great! but the server url is misspelled .

**Comment by vemonet** [comment]
Yep it works with absolute URIs and relative paths(e.g. `/api` or `v1`)

Going to try it with Smart API

**Comment by vemonet** [comment]
Smart API still not working even with absolute URL: https://smart-api.info/ui/ff8e602615d19577fa3759240dcce951
